name: master

on:
  push:
    branches:
    - master

jobs:
  # JOB to run change detection
  detectChanges:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      images: ${{ steps.filter.outputs.images }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: master
        filters: |
          images:
            - 'app/res/img/**'
          server:
            - 'server/**'
          replServer
            - 'replServer/**'
          app
            - 'app/**'
          serviceWorker
            - 'serviceWorker/**'
          dependencies
            - 'package.json'
          public
            - 'public/**'
          deployOption
            - '.deploy'


  buildApp: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 15
    
    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.app == 'true' }}
      uses: actions/checkout@master

    - name: Setting up node
      if: ${{ needs.detectChanges.outputs.app == 'true' }}
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      if: ${{ needs.detectChanges.outputs.app == 'true' }}
      run: npm i

    # - name: set environment variables
    #   uses: allenevans/set-env@v2.0.0
    #   with:
    #     GOOGLE_MAPS_API_KEY: '${{ secrets.MAPS_API_KEY }}'
    
    - name: "Building app"
      if: ${{ needs.detectChanges.outputs.app == 'true' }}
      run: npm run buildProdApp --if-present

    - name: "Copying files to remote"
      if: ${{ needs.detectChanges.outputs.app == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "${GITHUB_SHA}/public/dist"
        target: /var/www/html/xcenic/master
        overwrite: true

  buildServer: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 15
    
    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.server == 'true' }}
      uses: actions/checkout@master

    - name: Setting up node
      if: ${{ needs.detectChanges.outputs.server == 'true' }}
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      if: ${{ needs.detectChanges.outputs.server == 'true' }}
      run: npm i

    # - name: set environment variables
    #   uses: allenevans/set-env@v2.0.0
    #   with:
    #     GOOGLE_MAPS_API_KEY: '${{ secrets.MAPS_API_KEY }}'
    
    - name: "Building server"
      if: ${{ needs.detectChanges.outputs.server == 'true' }}
      run: npm run buildProdServer --if-present

    - name: "Copying files to remote"
      if: ${{ needs.detectChanges.outputs.server == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "${GITHUB_SHA}/server"
        target: /var/www/html/xcenic/master
        overwrite: true

  buildReplServer: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 15
    
    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.replServer == 'true' }}
      uses: actions/checkout@master

    - name: Setting up node
      if: ${{ needs.detectChanges.outputs.replServer == 'true' }}
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      if: ${{ needs.detectChanges.outputs.replServer == 'true' }}
      run: npm i

    # - name: set environment variables
    #   uses: allenevans/set-env@v2.0.0
    #   with:
    #     GOOGLE_MAPS_API_KEY: '${{ secrets.MAPS_API_KEY }}'
    
    - name: "Building repl server"
      if: ${{ needs.detectChanges.outputs.replServer == 'true' }}
      run: npm run buildProdReplServer --if-present

    - name: "Copying files to remote"
      if: ${{ needs.detectChanges.outputs.replServer == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "${GITHUB_SHA}/replServer"
        target: /var/www/html/xcenic/master
        overwrite: true


  buildServiceWorker: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 15
    
    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.serviceWorker == 'true' }}
      uses: actions/checkout@master

    - name: Setting up node
      if: ${{ needs.detectChanges.outputs.serviceWorker == 'true' }}
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      if: ${{ needs.detectChanges.outputs.serviceWorker == 'true' }}
      run: npm i

    # - name: set environment variables
    #   uses: allenevans/set-env@v2.0.0
    #   with:
    #     GOOGLE_MAPS_API_KEY: '${{ secrets.MAPS_API_KEY }}'
    
    - name: "Building service worker"
      if: ${{ needs.detectChanges.outputs.serviceWorker == 'true' }}
      run: npm run buildProdSw --if-present

    - name: "Copying files to remote"
      if: ${{ needs.detectChanges.outputs.serviceWorker == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        # todo service worker dist
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "${GITHUB_SHA}/public/sw.js"
        target: /var/www/html/xcenic/master
        overwrite: true

  compressImages: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 100

    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.images == 'true' }}
      uses: actions/checkout@master
      with:
        lfs: "true"

    - name: Setting up node
      if: ${{ needs.detectChanges.outputs.images == 'true' }}
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      if: ${{ needs.detectChanges.outputs.images == 'true' }}
      run: npm i image-web -g

    - name: Setting environment variables
      if: ${{ needs.detectChanges.outputs.images == 'true' }}
      uses: allenevans/set-env@v2.0.0
      with:
        UV_THREADPOOL_SIZE: '1' # otherwise may take up too much memory and cause action to be canceled.


    - name: "Compressing images"
      if: ${{ needs.detectChanges.outputs.images == 'true' }}
      run: npm run compressImages -- --legacyLogs

    - name: "Copying files to remote"
      if: ${{ needs.detectChanges.outputs.images == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "${GITHUB_SHA}/public/res/img/dist"
        target: /var/www/html/xcenic/master
        overwrite: true


  copyPublicAssets: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 15

    
    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.public == 'true' }}
      uses: actions/checkout@master

    - name: Copy public files
      if: ${{ needs.detectChanges.outputs.public == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "${GITHUB_SHA}/public"
        target: /var/www/html/xcenic/master
        overwrite: true

  dependencies: 
    runs-on: ubuntu-latest
    needs: [detectChanges]
    timeout-minutes: 15

    
    steps: 
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.dependencies == 'true' }}
      uses: actions/checkout@master

    - name: Copy dependency files
      if: ${{ needs.detectChanges.outputs.dependencies == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "package.json"
        target: /var/www/html/xcenic/master
        overwrite: true

    - name: Installing dependencies on remote
      if: ${{ needs.detectChanges.outputs.dependencies == 'true' }}
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/xcenic/master
          source ~/.nvm/nvm.sh
          nvm use default
          npm i

  deploy: 
    runs-on: ubuntu-latest
    needs: [detectChanges, buildApp, buildServer, buildReplServer, buildServiceWorker, compressImages, copyPublicAssets, dependencies]
    timeout-minutes: 15

    steps:
    - name: "checkout"
      if: ${{ needs.detectChanges.outputs.deployOption == 'true' }}
      uses: actions/checkout@master

    - name: Copy deploy option files
      if: ${{ needs.detectChanges.outputs.deployOption == 'true' }}
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: ".deploy"
        target: /var/www/html/xcenic/master
        overwrite: true


      # todo copy from temp storage to final

    
    - name: Restarting server
      if: ${{ (needs.detectChanges.outputs.deployOption == 'true') || (needs.detectChanges.outputs.server == 'true') || (needs.detectChanges.outputs.replServer == 'true') || (needs.detectChanges.outputs.dependencies == 'true') }}
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/xcenic/master
          source ~/.nvm/nvm.sh
          nvm use default
          wait-on ecosystem.config.js
          node pm2Reload.js