name: master

on:
  push:
    branches:
    - master

jobs:
  # JOB to run change detection
  detectChanges:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      pull-requests: read
    outputs:
      images: ${{ steps.filter.outputs.images }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          images:
            - 'app/res/img/**'


  build: 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps: 
    - name: "checkout"
      uses: actions/checkout@master

    - name: Setting up node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      run: npm i

    # - name: set environment variables
    #   uses: allenevans/set-env@v2.0.0
    #   with:
    #     GOOGLE_MAPS_API_KEY: '${{ secrets.MAPS_API_KEY }}'
    
    - name: "Building"
      run: npm run build --if-present

    - name: "Testing"
      run: npm test --if-present

    - name: "Copying files to remote"
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "public,server/dist,server/res,replServer/dist,replServer/res,.deploy"
        target: /var/www/html/xcenic/master
        tar_tmp_path: true

  compressImages: 
    needs: detectChanges
    if: ${{ needs.detectChanges.outputs.images == 'true' }}

    runs-on: ubuntu-latest
    timeout-minutes: 100

    steps: 
    - name: "checkout"
      uses: actions/checkout@master
      with:
        lfs: "true"


    - name: Setting up node
      uses: actions/setup-node@master
      with:
        node-version: '16.x'

    - name: Installing runner dependencies
      run: npm i image-web -g

    - name: Pull images
      run: git lfs pull

    - name: Setting environment variables
      uses: allenevans/set-env@v2.0.0
      with:
        UV_THREADPOOL_SIZE: '1' # otherwise may take up too much memory and cause action to be canceled.


    - name: "Compressing images"
      run: npm run compressImages -- --legacyLogs

    - name: "Copying files to remote"
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "public/res/img/dist"
        target: /var/www/html/xcenic/master
        tar_tmp_path: true


  dependencies: 
    runs-on: ubuntu-latest
    timeout-minutes: 15

    
    steps: 
    - name: "checkout"
      uses: actions/checkout@master

    - name: Copy dependency files
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        source: "package.json"
        target: /var/www/html/xcenic/master
        tar_tmp_path: true

    - name: Installing dependencies on remote
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/xcenic/master
          source ~/.nvm/nvm.sh
          nvm use default
          npm i

  deploy: 
    runs-on: ubuntu-latest
    needs: [build, dependencies, compressImages]
    timeout-minutes: 15

    steps:
    - name: Starting process
      uses: appleboy/ssh-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd /var/www/html/xcenic/master
          source ~/.nvm/nvm.sh
          nvm use default
          wait-on ecosystem.config.js
          node pm2Reload.js